// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lipvstajrfjjxddtypnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcHZzdGFqcmZqanhkZHR5cG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDcxODUsImV4cCI6MjA2NDEyMzE4NX0.LdSVBeLe03r00ZymL6cUebZk_kcj3a3SVncwocNUxvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});